In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Loading dataset

In [61]:

data = sns.load_dataset('tips')

In [62]:
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [63]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [64]:
data.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [65]:
#Checking the uniques classes in each columns

print(data["time"].unique())
print(data["smoker"].unique())
print(data["sex"].unique())
print(data["day"].unique())

['Dinner', 'Lunch']
Categories (2, str): ['Lunch', 'Dinner']
['No', 'Yes']
Categories (2, str): ['Yes', 'No']
['Female', 'Male']
Categories (2, str): ['Male', 'Female']
['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']

# Encoding the categorical valuues

In [66]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

label = LabelEncoder()
onehot = OneHotEncoder()

In [67]:
# label Encoding
data["sex"] = label.fit_transform(data["sex"])
data["smoker"] = label.fit_transform(data["smoker"])
data["time"] = label.fit_transform(data["time"])

In [68]:
# One-Hot Encoding
data = pd.get_dummies(data,columns=["day"],dtype=int)

In [70]:
data.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'time', 'size', 'day_Thur',
       'day_Fri', 'day_Sat', 'day_Sun'],
      dtype='str')

In [71]:
data.head()

,total_bill,tip,sex,smoker,time,size,day_Thur,day_Fri,day_Sat,day_Sun
0,16.99,1.01,0,0,0,2,0,0,0,1
1,10.34,1.66,1,0,0,3,0,0,0,1
2,21.01,3.50,1,0,0,3,0,0,0,1
3,23.68,3.31,1,0,0,2,0,0,0,1
4,24.59,3.61,0,0,0,4,0,0,0,1

In [72]:
X = data.drop(columns="smoker")
y = data["smoker"]

# Splitting data into train-test

In [74]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [75]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(183, 9)
(61, 9)
(183,)
(61,)

# Model Training

In [76]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train,y_train)

pred = gnb.predict(X_test)

In [84]:
# Metrices 

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

print(f"Accuracy: {accuracy_score(y_test, pred) * 100:.2f}%")
print("confusion matrix = \n", confusion_matrix(y_test,pred))
print("\nclassification report = \n", classification_report(y_test,pred))

Accuracy: 70.49%
confusion matrix =
 [[36  3]
 [15  7]]

classification report =
               precision    recall  f1-score   support

           0       0.71      0.92      0.80        39
           1       0.70      0.32      0.44        22

    accuracy                           0.70        61
   macro avg       0.70      0.62      0.62        61
weighted avg       0.70      0.70      0.67        61